name: eventmaster
description: Una aplicación para gestión de eventos
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  intl: ^0.20.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.5
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.2
  open_file: ^3.2.1
  url_launcher: ^6.1.11
  path_provider: ^2.1.1
  flutter_dotenv: ^6.0.0
  permission_handler: ^12.0.1
  http: ^1.1.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - images/


# platforms:
#   android:
#     pluginClass: none
#   ios:
#     pluginClass: none
